#! /bin/sh
#
# Check that the publication list is valid. 
#

set -e

#
# Check that all publications in kunegis.bib have a 'kunegiscat'. 
#

n="$(echo $(<kunegis.bib grep -E 'kunegiscat[[:space:]]*=[[:space:]]\{' | wc -l))"
m="$(echo $(<kunegis.bib grep -E '^[[:space:]]*@[[:space:]]*([a-z]+)[[:space:]]*\{' | wc -l))"

[ "$n" -ne "$m" ] && {
	echo >&2 "*** different numbers of publications:  $n != $m"
	exit 1
}

#
# Check that all 'kunegiscat' fields in kunegis.bib has valid values. 
#

<kunegis.bib sed -E -e '
	s,.*kunegiscat[[:space:]]*=[[:space:]]*\{[[:space:]]*([a-z]+)[[:space:]]*\}.*,\1,;t;d
' | while IFS= read -r cat ; do
	grep -q -F "(kunegiscat=$cat)" kunegis.bib || {
		echo >&2 "*** Invalid category '$cat'"
		exit 1
	}
done

exit 0
