#! /bin/sh
# 
# Get a single Bibtex field 
# 
# INVOCATION
# 
#	$0 $id $field
#
# INPUT FILES 
#	pubdb
#

id="$1"
field="$2"

ret="$(<pubdb sed -E -e '
s/^'"$id"'	'"$field"'	(.+)$/\1/
t
d
')"

if echo "$field" | grep -E -q ^url ; then
	ret="$(printf "%s\n" "$ret" | sed -E -e 's,#,\\#,g')"
fi

printf "%s\n" "$ret"
