#! /bin/sh

<kunegis.bib sed -E -e '
	s/^.*@[[:space:]]*[a-z]+[[:space:]]*\{[[:space:]]*([^, ]+)[[:space:]]*,.*$/\1/
        t
	s/^.*kunegiscat[[:space:]]*=[[:space:]]*\{[[:space:]]*([^} ]+)[[:space:]]*\}.*$/\1/
        t
        d
' | sed -E -e '$!N;s/\n/	/'  | 
tac
