#! /bin/sh
#
# INVOCATION
#	$0 $group
#

set -e

group=$1

[ "$verbose" ] && exec 6>&1 || exec 6>/dev/null 

printf '\\begin{itemize}\n'

while IFS= read -r line ; do
	id=$(echo "$line" | cut -f 1)
	cat=$(echo "$line" | cut -f 2)
	set +e
	echo >&6 ./is_group "$group" "$cat" 
	./is_group "$group" "$cat" 
	exitstatus=$?
	set -e
	if [ "$exitstatus" = 0 ] ; then
		./write_publication "$id"
	elif [ "$exitstatus" = 1 ] ; then
		: # nop
	else 
		echo >&2 "*** Internal error in ./is_group"
		exit 2
	fi
done

printf '\\end{itemize}\n'
