#! /bin/sh

sed -E -e '
s/^[[:space:]]*@([^{]+)[[:space:]]*\{[[:space:]]*([^, ]+)[[:space:]]*,.*$/\2	_	\1/
tnew
bother
:new
p
s/^(.+)	_	(.+)$/\1/
h
d
:other
s/^[[:space:]]*([^[:space:]=]+)[[:space:]]*=[[:space:]]*\{[[:space:]]*(.+)[[:space:]]*\}[[:space:]]*,[[:space:]]*$/\1	\2	/
tnormal
d
:normal
G
s/^(.+)	(.+)	(.+)$/\3	\1	\2/
'
