#! /bin/sh

sed -E -e '
s/^\s*@([^{]+)\s*\{\s*([^, ]+)\s*,.*$/\2	_	\1/
tnew
bother
:new
p
s/^(.+)	_	(.+)$/\1/
h
d
:other
s/^\s*([^[:space:]=]+)\s*=\s*\{\s*(.+)\s*\}\s*,\s*$/\1	\2	/
tnormal
d
:normal
G
s/^(.+)	(.+)	(.+)$/\3	\1	\2/
'
