#! /bin/sh
#
# Output the Latex code for the \item element for publication with
# Bibtex ID "$id". 
#
# Every line ends in 
#
#	.%nbibtex:$BIBTEXID
#
# INVOCATION 
# 
#    $0 $id
#
# INPUT FILES 
#	pubdb, field
#

set -e

id="$1"

tmpfile="${TMPDIR:-/tmp}/write_publication.$$"

bibtextype="$(./field "$id" _        )"
title="$(     ./field "$id" title    )"
author="$(    ./field "$id" author   )"
year="$(      ./field "$id" year     )"
journal="$(   ./field "$id" journal  )"
booktitle="$( ./field "$id" booktitle)"
pages="$(     ./field "$id" pages    )"
volume="$(    ./field "$id" volume   )"
number="$(    ./field "$id" number   )"
url="$(       ./field "$id" url      )"
url_presentation="$(./field "$id" url_presentation)"
url_poster="$(      ./field "$id" url_poster      )"
url_web="$(         ./field "$id" url_web         )"
url_video="$(       ./field "$id" url_video       )"
url_arxiv="$(       ./field "$id" url_arxiv       )"
url_data="$(        ./field "$id" url_data        )"
url_code="$(        ./field "$id" url_code        )"
url_media="$(       ./field "$id" url_media       )"
url_media2="$(      ./field "$id" url_media2      )"
url_citations="$(   ./field "$id" url_citations   )"
url_prize="$(       ./field "$id" url_prize       )"
url_nomination="$(  ./field "$id" url_nomination  )"

if printf "%s" "$title" | grep -q -E '[?]$' ; then
	endpunct=
else
	endpunct="."
fi
if [ -n "$url" ] ; then
	title_linked="\\href{$url}{$title$endpunct}"
else
	title_linked="$title$endpunct"
fi

author="$(printf "%s" "$author" | sed -E -e 's/ and /\
/g' | sed -E -e 's/^(.*), (.*)$/\2 \1/g;$!s/$/, /' | tr -d '\n')"

venue_part=
if [ -n "$journal" ] ; then
	venue_part="$venue_part, $(printf "\\")textit{$journal}"
fi
if [ -n "$booktitle" ] ; then
	venue_part="$venu_part, In: $(printf "\\")textit{$booktitle}"
fi

coordinates_part=
if [ -n "$volume" ] ; then 
	coordinates_part="${coordinates_part}$volume"
fi
if [ -n "$number" ] ; then
	coordinates_part="${coordinates_part}($number)"
fi
if [ -n "$pages" ] ; then
	if [ -n "$coordinates_part" ] ; then
		coordinates_part="${coordinates_part}:$pages"
	else
		coordinates_part="pp. $pages"
	fi
fi
if [ -n "$coordinates_part" ] ; then
	coordinates_part=", $coordinates_part"
fi

extra_part=
if [ "$bibtextype" = techreport ] ; then
	extra_part="$extra_part, Technical report"
fi
for extra_field in publisher series institution howpublished note issue ; do
	value="$(./field "$id" "$extra_field")"
	if [ -n "$value" ] ; then
		extra_part="$extra_part, $value"
	fi
done

margin_part=
if [ -n "$url" ] ; then
	margin_part="\\href{$url}{\faFileTextO}" 
fi
if [ -n "$url_arxiv" ] ; then
	margin_part="${margin_part} \\href{$url_arxiv}{\faFileExcelO}"
fi
if [ -n "$url_poster" ] ; then
	margin_part="${margin_part} \\href{$url_poster}{\faFilePictureO}"   # \faObjectGroup
fi
if [ -n "$url_presentation" ] ; then
	margin_part="${margin_part} \\href{$url_presentation}{\faSlideshare}"
fi
if [ -n "$url_citations" ] ; then
	margin_part="${margin_part} \\href{$url_citations}{\faQuoteRight}"  # \faComments
fi
if [ -n "$url_web" ] ; then
	margin_part="${margin_part} \\href{$url_web}{\faChain}" 
fi
if [ -n "$url_data" ] ; then
	margin_part="${margin_part} \\href{$url_data}{\faDatabase}" 
fi
if [ -n "$url_code" ] ; then
	margin_part="${margin_part} \\href{$url_code}{\faCog}" 
fi
if [ -n "$url_video" ] ; then
	margin_part="${margin_part} \\href{$url_video}{\faVideoCamera}"
fi
if [ -n "$url_media" ] ; then
	margin_part="${margin_part} \\href{$url_media}{\faNewspaperO}"
fi
if [ -n "$url_media2" ] ; then
	margin_part="${margin_part} \\href{$url_media2}{\faNewspaperO}"
fi
if [ -n "$url_prize" ] ; then
	margin_part="${margin_part} \\href{$url_prize}{\faStar}"
fi
if [ -n "$url_nomination" ] ; then
	margin_part="${margin_part} \\href{$url_nomination}{\faStarO}"
fi
if [ -n "$margin_part" ] ; then
	margin_part=" \\marginnote{$margin_part}"
fi

printf '\\item[{[\\publicationnumber]}]%s %s %s%s%s%s, %s.%%bibtex:%s\n' \
	"$margin_part" \
	"$title_linked" \
	"$author" \
	"$venue_part" \
	"$coordinates_part" \
	"$extra_part" \
	"$year" \
	"$id"
